Add zfs pool import support for zfs root
alpinelinux/mkinitfs pull request #4
Opened 2016-09-22 17:42 UTC by Klowner

2016-09-27 18:17 UTC, Klowner commented
One thing I've noticed while using this is that when I have zpools which span multiple disks, it will attempt to import all of them, resulting in "pool is already defined" messages at boot. This doesn't cause any problem, but I don't know if it's worth my time to add additional checking to see if the pool already exists.

😕  Input is welcome.

2016-10-30 13:50 UTC, jirutka commented
@ncopa could you please review this patch?

2016-11-25 17:15 UTC, ncopa requested changes
I think this needs rebase now. sorry.

2016-11-25 17:16 UTC, ncopa commented on initramfs-init.in
> +if [ "$KOPT_rootfstype" == "zfs" ]; then
use `=` instead of `==`

2016-11-25 17:16 UTC, Klowner commented
Will do!

On Fri, Nov 25, 2016, 11:15 AM Natanael Copa <notifications@github.com>
wrote:

> *@ncopa* requested changes on this pull request.
>
> I think this needs rebase now. sorry.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alpinelinux/mkinitfs/pull/4#pullrequestreview-10189685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAknhKZtrIEe6kkhQiboK7zqfBCCnbTks5rBxe6gaJpZM4KEK2e>
> .
>

2016-11-25 17:16 UTC, ncopa approved these changes
this lgtm. I mean last commit looks good.

2016-11-26 16:59 UTC, Klowner commented
rebased

2016-11-29 15:42 UTC, ncopa requested changes

2016-11-29 15:42 UTC, ncopa commented on nlplug-findfs.c
> +		blkid_get_cache(&cache, NULL);
we already have a [blkid cache](https://github.com/alpinelinux/mkinitfs/blob/master/nlplug-findfs.c#L317), which I think will always be initialized when reaching this point. see https://github.com/alpinelinux/mkinitfs/blob/master/nlplug-findfs.c#L912

In any case, we should reuse the same blkid_cache and not try set up a new one. This means that we need pass the cache or maybe even the conf struct as an arg to `start_zpool`

2016-11-29 15:53 UTC, ncopa commented on nlplug-findfs.c
> +			rc = find_bootrepos(ev->devnode, type, bootrepos, apkovls);
This hunk needs to be removed. `find_bootrepos` got renamed to `scandev` and `bootrepos` got replaced by `scanbootmedia` in 7673ee7d1ce6786a5471ead15513d62027c9756a

2016-11-29 16:20 UTC, ncopa commented
Can you please test if this works? It builds at least.

````diff
diff --git a/nlplug-findfs.c b/nlplug-findfs.c
index 52fac0d..3ff2a1d 100644
--- a/nlplug-findfs.c
+++ b/nlplug-findfs.c
@@ -497,23 +497,14 @@ static void start_lvm2(char *devnode)
                spawn_command(&spawnmgr, lvm2_argv, 0);
 }
 
-static void start_zpool(char *devnode)
+static void start_zpool(char *uuid)
 {
-       static blkid_cache cache = NULL;
-
-       if (cache == NULL)
-               blkid_get_cache(&cache, NULL);
-
-       char *uuid = blkid_get_tag_value(cache, "UUID", devnode);
        char *zpool_argv[] = {
                ZPOOL_PATH, "import", uuid,
                NULL
        };
        if (use_zpool && uuid)
                spawn_command(&spawnmgr, zpool_argv, 0);
-
-       if (uuid)
-               free(uuid);
 }
 
 static int read_pass(char *pass, size_t pass_size)
@@ -933,6 +924,7 @@ static int searchdev(struct uevent *ev, const char *searchdev, int scanbootmedia
                blkid_get_cache(&conf->blkid_cache, NULL);
 
        type = blkid_get_tag_value(conf->blkid_cache, "TYPE", ev->devnode);
+       uuid = blkid_get_tag_value(conf->blkid_cache, "UUID", ev->devnode);
 
        if (searchdev != NULL) {
                if (strncmp("LABEL=", searchdev, 6) == 0) {
@@ -940,7 +932,6 @@ static int searchdev(struct uevent *ev, const char *searchdev, int scanbootmedia
                        if (label && strcmp(label, searchdev+6) == 0)
                                rc = FOUND_DEVICE;
                } else if (strncmp("UUID=", searchdev, 5) == 0) {
-                       uuid = blkid_get_tag_value(conf->blkid_cache, "UUID", ev->devnode);
                        if (uuid && strcmp(uuid, searchdev+5) == 0)
                                rc = FOUND_DEVICE;
                }
@@ -955,11 +946,9 @@ static int searchdev(struct uevent *ev, const char *searchdev, int scanbootmedia
                } else if (strcmp("LVM2_member", type) == 0) {
                        start_lvm2(ev->devnode);
                } else if (strcmp("zfs_member", type) == 0) {
-                       start_zpool(ev->devnode);
+                       start_zpool(uuid);
                } else if (scanbootmedia) {
                        rc = scandev(conf, ev->devnode, type);
-               } else if (bootrepos) {
-                       rc = find_bootrepos(ev->devnode, type, bootrepos, apkovls);
                }
        }
 
````

2016-11-29 17:07 UTC, ncopa commented on initramfs-init.in
> +	ln -s /proc/mdstat /etc/mtab
shouldn't the symlink point to `/proc/mounts`? In any case, it sounds like an upstream bug.

2016-11-30 17:27 UTC, Klowner commented
I'll see if this works, sorry for the need for all the changes.

2016-12-08 15:09 UTC, Klowner commented
@ncopa Included your suggestions/changes and tested yesterday, works great for me! :+1:

2016-12-26 13:54 UTC, closed without merging