Tidy test script and fix output
alpinelinux/mkinitfs pull request #9
Opened 2017-02-21 06:38 UTC by pickfire

2017-04-03 15:06 UTC, 7heo requested changes

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	dd if=/dev/zero of=block count=10 bs=1M 2>&1 | sed 's/^/\t/'
This `global` flag is needed for the multi-line outputs.

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	printf "%s" "$passphrase" | sudo cryptsetup open -q $block temp-test - 2>&1 | sed 's/^/\t/'
`luksOpen` is replaced by `open --type luks`, not only by `open`.
The `global` `sed(1)` flag is needed for the multi-line outputs.

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	shift
:+1:

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	proof=$(date "+proof:%s" | sudo tee local-mount/proof)
No. This is terribly wrong. We need to write the data first and **then** fetch it from the filesystem, to ensure that it is present. :-1:

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	echo
Why?

2017-04-03 15:06 UTC, 7heo commented on test.sh
> +	sudo cryptsetup close temp-test
Unlike the `open --type luks` syntax, this is the correct one (the man documents it as the command `luksClose` is aliased to). :+1:

2017-04-04 01:42 UTC, pickfire commented on test.sh
> +	printf "%s" "$passphrase" | sudo cryptsetup luksFormat -q $block - 2>&1 | sed 's/^/\t/'
@7heo The `global` is required only for repeats in multi line output, substituting `^` would not give us any repeats.

2017-04-04 01:42 UTC, pickfire commented on test.sh
> +	sudo losetup $block block 2>&1 | sed 's/^/\t/'
@7heo The `global` is required only for repeats in multi line output, substituting `^` would not give us any repeats.

2017-04-04 01:43 UTC, pickfire commented on test.sh
> +	printf "%s" "$passphrase" | sudo cryptsetup open -q $block temp-test - 2>&1 | sed 's/^/\t/'
Okay, I will change it with `open --type luks`.

2017-04-04 01:45 UTC, pickfire commented on test.sh
> +	proof=$(date "+proof:%s" | sudo tee local-mount/proof)
Ah, I think I understand what you mean.

2017-04-04 01:45 UTC, pickfire commented on test.sh
> +	echo
To clean up the output.

2017-04-04 01:49 UTC, pickfire commented on test.sh
> +	dd if=/dev/zero of=block count=10 bs=1M 2>&1 | sed 's/^/\t/'
@7heo The `global` is required only for repeats in multi line output, substituting ^ would not give us any repeats.

2017-04-04 16:18 UTC, 7heo commented on test.sh
> +	echo
How does adding a line clean the output?

2017-04-04 16:21 UTC, 7heo commented on test.sh
> +	dd if=/dev/zero of=block count=10 bs=1M 2>&1 | sed 's/^/\t/'
Actually global is required in multi-line outputs, but not for `sed`, which parses lines one by one. So this is correct.

2017-04-04 16:21 UTC, 7heo commented on test.sh
> +	sudo losetup $block block 2>&1 | sed 's/^/\t/'
See above.

2017-04-04 16:21 UTC, 7heo commented on test.sh
> +	printf "%s" "$passphrase" | sudo cryptsetup luksFormat -q $block - 2>&1 | sed 's/^/\t/'
See above.

2017-04-04 16:23 UTC, 7heo requested changes
Could you please squash this commit in the previous one?

2017-04-04 16:42 UTC, pickfire commented
How do I do that in github?

2017-04-04 16:53 UTC, 7heo commented
Do it locally and issue a `git push -f`

2017-04-05 11:55 UTC, 7heo commented
@pickfire also this needs a rebase now.

2017-04-05 14:03 UTC, pickfire commented
Updated.

2017-10-18 03:42 UTC, closed without merging